name: Nightly builds

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: nightly
    - name: Merge master
      run: git merge master
    - name: Push nightly
      run: git push
